#if !canImport(ObjectiveC)
import XCTest

extension ExamplesTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ExamplesTests = [
        ("testPluralize", testPluralize),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ExamplesTests.__allTests__ExamplesTests),
    ]
}
#endif
