#if !canImport(ObjectiveC)
import XCTest

extension PluralizeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PluralizeTests = [
        ("testPluralize", testPluralize),
    ]
}

extension ViewModelTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ViewModelTests = [
        ("testViewModelMessage", testViewModelMessage),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(PluralizeTests.__allTests__PluralizeTests),
        testCase(ViewModelTests.__allTests__ViewModelTests),
    ]
}
#endif
