#if !canImport(ObjectiveC)
import XCTest

extension AnyEquatableTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AnyEquatableTests = [
        ("testDescription", testDescription),
        ("testEquatableConformance", testEquatableConformance),
    ]
}

extension ExpectTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ExpectTests = [
        ("testExpect", testExpect),
        ("testOmit", testOmit),
    ]
}

extension RecipeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RecipeTests = [
        ("testAssertInit", testAssertInit),
        ("testErrorAssert", testErrorAssert),
        ("testFailingAssert", testFailingAssert),
        ("testInitClosure", testInitClosure),
        ("testInitTimeout", testInitTimeout),
        ("testInvalidCompletion", testInvalidCompletion),
        ("testPassingAssert", testPassingAssert),
    ]
}

extension WhenTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__WhenTests = [
        ("testWhen", testWhen),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AnyEquatableTests.__allTests__AnyEquatableTests),
        testCase(ExpectTests.__allTests__ExpectTests),
        testCase(RecipeTests.__allTests__RecipeTests),
        testCase(WhenTests.__allTests__WhenTests),
    ]
}
#endif
