name: Test

on: push

jobs:
  test_xcode:
    strategy:
      matrix:
        include:
          - os: macos-11
            swift: "~5.3"
          - os: macos-11
            swift: "~5.4"
          - os: macos-11
            swift: "~5.5"
          - os: macos-12
            swift: "~5.6"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: mxcl/xcodebuild@v1
        with:
          swift: ${{ matrix.swift }}

  test-spm:
    strategy:
      matrix:
        swift: ["5.3", "5.4", "5.5", "5.6"]
    runs-on: ubuntu-latest
    container:
      image: swift:${{ matrix.swift }}
    steps:
      - uses: actions/checkout@v2
      - run: make test/spm
